Metrics/LineLength:
  Max: 512

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

# RuboCop changed its mind on preferred style
Style/SignalException:
  Enabled: false
