update:
  githubActions: true

autoDedupe: true
saveTypes: true

packages:
  - cdk
  - cdk/docker/mediaflux

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lefthook: true
  unrs-resolver: true
