location ~ ^/repository/ {
    if ($request_uri ~ ^/repository/([^/]+)/([^/]+)/(.+)$) {
        return 301 https://$host/file?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2F$1%2F$2%2F$3;
    }
    if ($request_uri ~ ^/repository/([^/]+)/([^/]+)$) {
        return 301 https://$host/object?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2F$1%2F$2;
    }
    if ($request_uri ~ ^/repository/([^/]+)$) {
        return 301 https://$host/collection?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2F$1;
    }
}

location ~ ^/collections/ {
    if ($request_uri ~ ^/collections/([^/]+)/items/([^/]+)$) {
        return 301 https://$host/object?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2F$1%2F$2;
    }
    if ($request_uri ~ ^/collections/([^/]+)$) {
        return 301 https://$host/collection?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2F$1;
    }
}
